spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
          - id: account-service
            uri: lb://account-service
            predicates:
              - Path=/v1/account/**
          - id: transaction-service
            uri: lb://transaction-service
            predicates:
              - Path=/v1/transactions/**
          - id: customer-service
            uri: lb://customer-service
            predicates:
              - Path=/v1/customer/**
      discovery:
        locator:
          enabled: true

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    service-url:
      default-zone: "http://localhost:8761/"
  instance:
    prefer-ip-address: true


